---
stats_dir: '/global/cscratch1/sd/feng045/waccem/mcs_global/global/stats/'
pixelfile_dir: '/global/cscratch1/sd/feng045/waccem/mcs_global/global/mcstracking/'
ar_dir: '/global/cscratch1/sd/feng045/waccem/AR_Tempest_hourly/'
tc_file: '/global/cscratch1/sd/feng045/waccem/IBTrACS/ibtracs_2000_2020.nc'
mcsstats_filebase: 'mcs_tracks_final_'
pixel_filebase: 'mcstrack_'
landmask_file: '/global/cscratch1/sd/feng045/waccem/mcs_global/map_data/IMERG_landmask_180W-180E_60S-60N.nc'
output_dir: '/global/cscratch1/sd/feng045/waccem/mcs_global/global/stats/'
# Precipitation variable name
pcpvarname: 'precipitation'
# Dask workers and threads
n_workers: 10
threads_per_worker: 1
# Rain rate threshold to define a PF [mm/h]
rr_min: 2.0
# Pixel size [km]
pixel_radius: 10.0  
# Minimum PF area threshold [km^2]
pf_min_area_thresh: 0
# # Threshold of pixel-level land fraction to define a land pixel [%]
# landfrac_thresh: 90