---
# stats_dir: '/global/cscratch1/sd/feng045/E3SM/SCREAMv0/gpm_1200x3600/pyflex/stats/'
# pixelfile_dir: '/global/cscratch1/sd/feng045/E3SM/SCREAMv0/gpm_1200x3600/pyflex/mcstracking/'
stats_dir: '/global/cscratch1/sd/feng045/E3SM/SCREAMv0/gpm_1200x3600/pyflex/stats_ccs2h10k_pf0duration/'
pixelfile_dir: '/global/cscratch1/sd/feng045/E3SM/SCREAMv0/gpm_1200x3600/pyflex/mcstracking_ccs2h10k_pf0duration/'
# mcsstats_filebase: 'robust_mcs_tracks_'
mcsstats_filebase: 'mcs_tracks_final_'
pixel_filebase: 'mcstrack_'
landmask_file: '/global/cscratch1/sd/feng045/E3SM/SCREAMv0/maps/IMERG_Tb_landseamask_1200x3600_0-360.nc'
# output_monthly_dir: '/global/cscratch1/sd/feng045/E3SM/SCREAMv0/gpm_1200x3600/pyflex/stats/'
output_monthly_dir: '/global/cscratch1/sd/feng045/E3SM/SCREAMv0/gpm_1200x3600/pyflex/stats_ccs2h10k_pf0duration/'
# Precipitation variable name
pcpvarname: 'precipitation'
# Dask workers and threads
n_workers: 32
threads_per_worker: 1
# Rain rate threshold to define a PF [mm/h]
rr_min: 2.0
# Pixel size [km]
pixel_radius: 10.0  
# Minimum PF area threshold [km^2]
pf_min_area_thresh: 0
# Threshold of pixel-level land fraction to define a land pixel [%]
landfrac_thresh: 90