#!/bin/bash
#SBATCH --job-name=asia_3D
#SBATCH -A m2645
#SBATCH --time=04:00:00
#SBATCH --output=log_mcs_era5_asia_3d_%A_%a.log
#SBATCH -q regular
#SBATCH -N 1
#SBATCH -c 64
#SBATCH -C haswell
###SBATCH --exclusive
#SBATCH --mail-type=END
#SBATCH --mail-user=zhe.feng@pnnl.gov

# To submit the job for a specific range of parts:
# sbatch --array=<indexlist>[%<limit>] slurm_jobarray.sh
# For example, to submit all 20 jobs, but limit to running 2 at a time:
# sbatch --array=1-20%2 slurm_jobarray.sh
# For running a number of specific jobs:
# sbatch --array=3,5,12,15-18%6 slurm_jobarray.sh

date
conda activate /global/common/software/m1867/python/py38

# Takes a specified line ($SLURM_ARRAY_TASK_ID) from the task file
LINE=$(sed -n "$SLURM_ARRAY_TASK_ID"p tasks_era5_asia_3d)
echo $LINE
# Run the line as a command
$LINE

date
