#!/bin/bash
#SBATCH --job-name=VAR_DATES
#SBATCH -A m1867
#SBATCH --time=01:30:00
#SBATCH -p regular
##SBATCH -p debug
#SBATCH --output=log_mcs_era5_VAR_DATES_4scream.log
#SBATCH -N 1
#SBATCH -c 32
#SBATCH -C haswell
#SBATCH --exclusive
#SBATCH --mail-type=END
#SBATCH --mail-user=zhe.feng@pnnl.gov
date
conda activate /global/common/software/m1867/python/py38
cd /global/homes/f/feng045/program/gpm_mcs_post/
python calc_imerg_mcs_era5_3d.py BASENAME VAR config_gpm_era5_3d_4scream.yml DATES
date
